# Generated by Django 4.2.20 on 2025-07-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bingorooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_text", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "bingorooms",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Bingos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_text", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "bingos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserBingoCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_text", models.CharField(max_length=50)),
                ("is_checked", models.BooleanField()),
                ("position", models.IntegerField()),
            ],
            options={
                "db_table": "user_bingo_cases",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ValidatedCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_checked", models.BooleanField()),
                (
                    "bingoroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bingo.bingorooms",
                    ),
                ),
            ],
            options={
                "db_table": "validated_cases",
                "managed": True,
            },
        ),
    ]
