# Generated by Django 4.2.20 on 2025-07-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bingo", "0001_initial"),
        ("room", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userbingocases",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="room.rooms"
            ),
        ),
        migrations.AddField(
            model_name="userbingocases",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bingorooms",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="room.adminrooms"
            ),
        ),
        migrations.AddField(
            model_name="bingorooms",
            name="bingo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="bingo.bingos"
            ),
        ),
    ]
