# Generated by Django 4.2.20 on 2025-07-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bingo", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbingocases",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userbingocases",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="validatedcases",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
