# Generated by Django 4.2.20 on 2025-07-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bingo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prediction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminrooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "adminrooms",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RoomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField()),
                ("close_at", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en cours", "en cours"),
                            ("terminé", "terminé"),
                            ("annulé", "annulé"),
                        ],
                        default="en cours",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("img_team1", models.CharField(default="", max_length=50)),
                ("img_team2", models.CharField(default="", max_length=50)),
                ("score_team1", models.IntegerField(default=0)),
                ("score_team2", models.IntegerField(default=0)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="room.adminrooms",
                    ),
                ),
                (
                    "bingoroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bingo.bingorooms",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="rooms_joined",
                        through="room.RoomMembership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="prediction.predictions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="roommembership",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.rooms"
            ),
        ),
        migrations.AddField(
            model_name="roommembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="adminrooms",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.rooms"
            ),
        ),
        migrations.AddField(
            model_name="adminrooms",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roommembership",
            unique_together={("user", "room")},
        ),
        migrations.AlterUniqueTogether(
            name="adminrooms",
            unique_together={("user", "room")},
        ),
    ]
