# Generated by Django 4.2.20 on 2025-07-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rooms",
            name="admin",
        ),
    ]
