# Generated by Django 4.2.20 on 2025-07-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prediction", "0001_initial"),
        ("bingo", "0003_alter_userbingocases_is_checked_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0002_remove_rooms_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rooms",
            name="user",
        ),
        migrations.AlterField(
            model_name="adminrooms",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="bingoroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bingo.bingorooms",
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="close_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="prediction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="prediction.predictions",
            ),
        ),
    ]
