# Generated by Django 4.2.20 on 2025-07-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminrooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "adminrooms",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Bingorooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_text", models.CharField(max_length=50)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.adminrooms",
                    ),
                ),
            ],
            options={
                "db_table": "bingorooms",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Bingos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_text", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "bingos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Predictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=50)),
                ("respons", models.CharField(max_length=50)),
                ("start_at", models.TimeField()),
                ("end_at", models.TimeField()),
                ("status", models.CharField(max_length=50)),
                ("timer", models.TimeField()),
                ("is_validated", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "predictions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateField()),
                ("close_at", models.DateField()),
                ("status", models.CharField(max_length=50)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.adminrooms",
                    ),
                ),
                (
                    "bingoroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.bingorooms",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.predictions",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ValidatedCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_checked", models.BooleanField()),
                (
                    "bingoroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.bingorooms",
                    ),
                ),
            ],
            options={
                "db_table": "validated_cases",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("update_at", models.TimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.rooms"
                    ),
                ),
            ],
            options={
                "db_table": "user_scores",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserBingoCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("case_text", models.CharField(max_length=50)),
                ("is_checked", models.BooleanField()),
                ("position", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.rooms"
                    ),
                ),
            ],
            options={
                "db_table": "user_bingo_cases",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Extendusers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=50)),
                ("img", models.CharField(max_length=50)),
                ("room_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "extendusers",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="bingorooms",
            name="bingo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.bingos"
            ),
        ),
    ]
