# Generated by Django 4.2.20 on 2025-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_adminrooms_user_id_remove_rooms_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="img_team1",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="rooms",
            name="img_team2",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="rooms",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="rooms",
            name="score_team1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rooms",
            name="score_team2",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="status",
            field=models.CharField(
                choices=[
                    ("en cours", "en cours"),
                    ("terminé", "terminé"),
                    ("annulé", "annulé"),
                ],
                default="en cours",
                max_length=50,
            ),
        ),
    ]
